version: "3.4"
services:
  dbp_postgres_db:
    container_name: dbp_postgres_db
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 15432:5432
    volumes:
      - db:/var/lib/postgresql:data
volumes:
  db:
    driver: local
