version: "3.4"
services:
  dbp:
    container_name: dbp
    image: ${DB_TARGET_IMAGE}
    restart: always
    environment:
      - DB_USER=system
      - DB_PASSWORD=system
    ports:
      - 15432:5432
    volumes:
      - db:/var/lib/${DB_TARGET_VOLUME}:data
volumes:
  db:
    driver: local
