---
version: "3.4"
services:
  dbp:
    container_name: dbp
    image: postgres:16.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    ports:
      - 15432:5432
    volumes:
      - db:/var/lib/postgresql:data
volumes:
  db:
    driver: local
