version: "3.4"
services:
  dbp_postgres_db:
    container_name: dbp_postgres_db
    image: ${DB_TARGET_IMAGE}
    restart: always
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    ports:
      - 15432:5432
    volumes:
      - db:/var/lib/${DB_VOLUME}:data
volumes:
  db:
    driver: local
