DROP TABLE IF EXISTS Cliente;
CREATE TABLE Cliente (
    cli_cod INTEGER PRIMARY KEY,
    cli_nome VARCHAR(30),
    cli_ativo BOOLEAN DEFAULT TRUE,
    cli_data_nasc DATE
);

INSERT INTO Cliente VALUES (1, 'Maria', 0, '1/10/1988');

SELECT
    CONSTRAINT_NAME,
    CONSTRAINT_TYPE,
    STATUS,
    CHECK_CLAUSES AS SEARCH_CONDITION 
FROM
    INFORMATION_SCHEMA.TABLE_CONSTRAINTS
WHERE
    TABLE_NAME = 'CLIENTE';
