---
version: '3.1'
services:
  oracle-db:
    image: container-registry.oracle.com/database/enterprise:latest
    environment:
      - ORACLE_SID=ORCLCDB
      - ORACLE_PDB=ORCLPDB1
      - ORACLE_PWD=Oracle_123
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - 1521:1521
    volumes:
      - oracle-data:/opt/oracle/oradata
      - oracle-backup:/opt/oracle/backup
    healthcheck:
      test:
        - "CMD"
        - "sqlplus"
        - "-L"
        - "sys/Oracle_123@//localhost:1521/ORCLCDB as sysdba"
        - "@healthcheck.sql"
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  oracle-data:
  oracle-backup:
